#!/bin/bash

set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
readonly DIR

if ! command -v terraform-docs > /dev/null; then
  echo "terraform-docs is missing."
  exit 1
fi

pushd "${DIR}/.." > /dev/null
terraform-docs markdown . > README.md
popd  > /dev/null
